site_name: MeshCore Docs
site_url: !ENV [MKDOCS_SITE_URL, 'https://meshcore-dev.github.io/meshcore/']
site_description: Documentation for the open source MeshCore firmware

repo_name: !ENV [MKDOCS_REPO_NAME, 'meshcore-dev/meshcore']
repo_url: !ENV [MKDOCS_REPO_URL, 'https://github.com/meshcore-dev/meshcore/']
edit_uri: !ENV [MKDOCS_EDIT_URI, 'edit/main/docs/']

theme:
  name: material
  logo: _assets/meshcore.svg
  features:
    - content.action.edit
    - content.code.copy
    - search.highlight
    - search.suggest

extra_css:
  - _stylesheets/extra.css
  - _stylesheets/telemetry_decoder.css
  - _stylesheets/filter_tool.css

extra_javascript:
  - _javascript/telemetry_decoder.js
  - _javascript/filter_tool.js
