; Heltec V3 Full Companion 1.17.1.8 preview3. See README.txt for source and pairing.
[platformio]
extra_configs =
  platformio.ini
  variants/*/platformio.ini

[env:Heltec_v3_companion_radio_full_preview3]
extends = env:Heltec_v3_companion_radio_full
board_build.flash_mode = dio
board_build.partitions = default_8MB.csv
build_unflags =
  -DMAX_CONTACTS=350
  -DLORA_FREQ=869.618
  -DLORA_SF=8
  -DDISABLE_WIFI_OTA=1
  -fexceptions
build_flags =
  ${env:Heltec_v3_companion_radio_full.build_flags}
  -D MAX_CONTACTS=100
  -D COMPANION_RADIO_FULL=1
  -D ENABLE_USB_INTERFACE=1
  -D BLE_PIN_CODE=123456
  -D ENABLE_OTA=1
  -UOTA_FLASH_STORE
  -UOTA_SD_STORE
  -UDISABLE_LORA_OTA
  -UWEBCONFIG_DISABLED
  -UDISABLE_WIFI_OTA
  -D OTA_SEEDER_ONLY=1
  -D MOTA_TARGET_ID=0
  -D WIFI_OTA_SEEDER=1
  -D COMPANION_FEATURE_TEMP_RADIO=1
  -D COMPANION_FEATURE_OTA_CLI=1
  -D COMPANION_FEATURE_USB_MOTA_SOURCE=1
  -D COMPANION_FEATURE_NETWORK_TERMINAL=1
  -D COMPANION_FEATURE_MEMORY_DIAGNOSTICS=1
  -D MESHCORE_EXPANDED_PARTITION_PROFILE=1
  -D LIGHTWEIGHT_WIFI_OTA=1
  -D MESH_DEBUG=1
  -D MESH_PACKET_LOGGING=1
  -D MESH_USE_NIMBLE_ARDUINO=1
  -D CONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
  -D CONFIG_BT_NIMBLE_ROLE_CENTRAL_DISABLED=1
  -D CONFIG_BT_NIMBLE_ROLE_OBSERVER_DISABLED=1
  -D LORA_FREQ=910.525
  -D LORA_BW=62.5
  -D LORA_SF=7
  -D LORA_CR=5
  -D MESHCORE_USA_RADIO_PRESET=1
  -D CASCADE_PROFILE=1
  -D DEFAULT_PATH_HASH_MODE=2
  -D DEFAULT_LOOP_DETECT=1
  -D DEFAULT_CAD_ENABLED=0
  -D DEFAULT_RX_DELAY_BASE=2.0f
  -D DEFAULT_AGC_RESET_INTERVAL_SECONDS=8
  -D DEFAULT_ADVERT_INTERVAL_MINUTES=0
  -D DEFAULT_FLOOD_ADVERT_INTERVAL_HOURS=83
  -D DEFAULT_MULTI_ACKS=1
  -D DEFAULT_MANUAL_ADD_CONTACTS=1
  -D DEFAULT_AUTOADD_CONFIG=0
  -D DEFAULT_POWERSAVING_ENABLED=1
  -D DEFAULT_RXPS_ENABLED=1
  -D DEFAULT_RXPS_LEVEL=8
  -D DEFAULT_RXPS_PREAMBLE=16
  -D RXPS_FIXED_ENABLED=1
  -D RXPS_FIXED_LEVEL=8
  -D RXPS_FIXED_PREAMBLE=16
  -D DEFAULT_WIFI_POWER_SAVE_MODE=0
  -D FIRMWARE_VERSION='"v1.17.1.8-preview3"'
  -D FIRMWARE_BUILD_DATE='"02-Oct-2026"'
  -D FIRMWARE_BUILD_EPOCH=1790928488
  -D OTA_VARIANT='"Heltec_v3_companion_radio_full"'
  -fno-exceptions
build_src_filter =
  ${env:Heltec_v3_companion_radio_full.build_src_filter}
  +<helpers/ota/*.cpp>
  +<helpers/ota/detools/detools.c>
lib_deps =
  ${env:Heltec_v3_companion_radio_full.lib_deps}
  h2zero/NimBLE-Arduino @ 2.5.1
lib_ignore = ESP32 BLE Arduino
