[platformio]
default_envs = sensecap_indicator_rp2040_font
src_dir = src

[env:sensecap_indicator_rp2040_font]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#4e22a0dcdd94eead72fdf56ea59a3d7c8aa2f379
board = seeed_indicator_rp2040
framework = arduino
monitor_speed = 115200
upload_protocol = picotool
build_flags =
  -Wall
  -Wextra
